### ISSUE TITLE
Rethink CSM / PowerSpectra valid frequency indexing (again)

### ISSUE THREAD

**Issue by gherold** [acoular/acoular#151]
Current PowerSpectra.freq_range adds easier access than ind_low/ind_high to limit calculated frequencies, but still is not very user-friendly if user
- wants to calculate only one discrete frequency band (has to find next frequency to add as upper limit)
- wants to calculate a list of discrete frequencies, omitting some in-between (not currently possible)
- wants to calculate a distinct band width around frequencies, e.g. 3rd-octave (freq limits have to be calculated "by hand")

The cleanest solution would be to let the Beamformer decide which frequencies will be calculated (depending on what is asked).

**Comment by esarradj** [comment]
I second the idea. However, this is difficult to achieve with the present API.
The result property of the beamformer is an array-like variable, which can be used as whole, or just in part (indexed). The question is, shall the computation be triggered, when `b.result` is referenced? Then, all frequencies will be calculated. This is the current behaviour (+ freqs limited by ind_low/ind_high). Or should the result only be computed when `b.result[i:j]` is referenced. This would require to meddle with pytables, numpy and pyh5 classes and derive a special intelligent data type :-(

**Comment by gherold** [comment]
Definitely do not calculate all frequencies if they're not asked, so something like the second suggestion.
The intelligence could be put in the `_get_result` function (possibly with additional parameters or traits) and shouldn't require too much meddling.

**Comment by esarradj** [comment]
Presently `b.result` is either of type `numpy.ndarray` or `h5py.Dataset` or `tables.(E)Array`. All these have a basic array interface and thus it makes mostly no notable difference. 

However, if we want to compute on demand we would have to overload the [] operator for all these classes, possibly also the parallel versions. we would have to support strides, ellipsis etc. I have no idea how to achieve this. On the other hand, if we introduce new parameters or traits or functions, this breaks compatibility. It is already possible to set ind_low/ind_high in an intelligent programmatic manner, what would additional traits add here?

**Comment by esarradj** [comment]
Another idea would be to implement a special behaviour for `BeamformerBase.synthetic` where only those results are computed that are needed for the frequency band. This is however, not easy to implement because presently calculation takes place in `BeamformerBase.calc` which is called with arrays of fixed size as arguments that return the result of the computation. These arrays or array-like objects are created within `BeamformerBase.result`, so there is no point calling it from somewhere else. It looks like
* internal structure inclusive caching mechanisms has to be reworked entirely
* `BeamformerBase.calc` has to be changed for all derived classes

The latter might even be a good idea, because there is code that repeats itself in all these classes.

**Comment by esarradj** [comment]
A not so complicated approach to the problem could also be to require the user to get the result through `synthetic` in order to make use of the computing time savings. Within `synthetic`,
1. the `ind_low` and `ind_high` values are saved to temporary variables
2. the limits for the requested frequency band are set in `ind_low` and `ind_high`
3. computation is triggered
4. original values of `ind_low` and `ind_high` are restored
5. result is returned

This way, we do not need to meddle with `calc` or caching or anything
