### ISSUE TITLE
Make parallel CPU usage settable via acoular.config

### ISSUE THREAD

**Issue by adku1173** [acoular/acoular#165]
Sometimes it is inconvenient that Acoular always uses the parallel=true mode with Numba. When running multiple Python processes in parallel, this setting can cause a dramatic slowdown of the calculations. 

Suggest to make the parallel option a global setting that can be adjusted via the acoular.config object.

**Comment by esarradj** [comment]
I think this can be perfectly controlled by the different [options](http://numba.pydata.org/numba-doc/latest/user/threading-layer.html#setting-the-number-of-threads) Numba itself offers:
- setting an environment variable (convenient for use on a cluster)
- using the [function](http://numba.pydata.org/numba-doc/latest/user/threading-layer.html#numba.set_num_threads) Numba offers (e.g. for benchmarking/tuning purposes)

Because I do not see how to improve this, I think we do not need to include this in Acoular too.

**Comment by adku1173** [comment]
Perfect, I did not know that the possibility of setting an environment variable or using a function exists. I'll close this issue.
