### ISSUE TITLE
Questions about example 2

### ISSUE THREAD

**Issue by TonyStudent** [acoular/acoular#19]
Dear sir or madam
I have some qustions to want communication with you. First , my English is very bad. So i'm very grateful you can read this message.
One question, the example2 have a moving source and fixed source.When i was changed the location of fixed source , whatever how to change, the fixed map doesn't show the fixed location. In this map ,Only show the trace of moving source,why?
Another question,  in figure2(moving focus map) and figure3(time domain fixed focus and time domain moving focus ),why the location of (0,0) has been marked. what does this mean?
At the end, i hope you can solve my questions.

**Comment by gherold** [comment]
The moving source is masking the stationary source; you'd have to change the signal amplitude of the two for a different result (using the `rms` trait of the WNoiseGenerator and SineGenerator).

Regarding your second question I assume that you mean the apparent source in the center, where there should'nt be one. This is due to the side lobes of the rotating source, whose energy adds up in the center/axis of rotation. At other positions, this energy is more spread out. So, this is an artifact from classic beamforming.
