### ISSUE TITLE
Where is the fixed point source about example2.py's result?

### ISSUE THREAD

**Issue by Qinstudy** [acoular/acoular#20]
Hello,the developer team! I want to use the moving source and fixed point source.After I read the example2.py code, I can't understand the result meaning of  example2.py. I tried to modify the code:P1 = PointSource(signal=n1, mpos=m, loc=(0,2.5,4)). The modification of loc=(0,2.5,4) is loc=(0,1,4). But I find the position of the fixed piont source has not changed, and the results have been found to be the same as those given by example2.py at http://www.acoular.org/. 
Is it the impact of the cache mechanism, if it is the impact of the cache mechanism, how to eliminate this cache mechanism？
In the all ,I can't find the location of the fixed sound source in your example2.py's results. Can you tell me where is the fixed point source in the output example2.py's three pictures ? Ask your team again and thank you for your generosity!

**Comment by gherold** [comment]
This behaviour could not be reproduced. It could happen if the simulated data is stored in an h5 file and loaded from there to do the beamforming (e.g. as is done in the acoular_demo.py), but this is not the case here (and will be fixed in the upcoming release). 
However, the changes you introduced lead only to subtle changes in the result -- look at the first two plots in Figure 3. They are slightly different at the upper half (where the stationary source is visible)
