### ISSUE TITLE
Github CI test pipeline sporadically fails for macos

### ISSUE THREAD

**Issue by adku1173** [acoular/acoular#209]
Error:
`run_tests.sh: line 8:  1871 Illegal instruction: 4  python -m unittest discover -v -p "test_*.py"
Error: Process completed with exit code 132.`

However, rerunning the pipeline resolves the problem.

**Comment by adku1173** [comment]
If the workflow is adjusted to use `run_tests_osx.sh`, the same problem occurs with python 3.11 
`run_tests_osx.sh: line 8:  1959 Illegal instruction: 4  python3 -m unittest discover -v -p "test_*.py"`

**Comment by adku1173** [comment]
After some logging with the existing test pipeline and different Mac OS versions, the problem seems to be the CPU's FMA feature's availability. 

If we compare the two workflow runs for the same macOS image and Python version (3.10):

ProductVersion:	12.7.4
BuildVersion:	21H1123
i386

* [Run1 (failed)](https://github.com/adku1173/acoular/actions/runs/8735322584/job/23967868387)

  -  FMA not available (CPU: Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz)

* [Run 2 (succeeded)](https://github.com/adku1173/acoular/actions/runs/8735500283/job/23968382509)

  - FMA available (CPU: Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz)

As we use SIMD instructions via Numba, this presumably causes the problem.

**Comment by esarradj** [comment]
Numba does autodetect (?) the CPU features, see [here](https://numba.pydata.org/numba-doc/dev/reference/envvars.html), so I have some doubts that it is to blame

**Comment by esarradj** [comment]
The choice of hardware for macos-latest is nondeterministic (see [here](https://github.com/actions/runner-images/issues/8642#issuecomment-1824251689) ) and the problem may go away eventually, when macos-latetest refers not to macos-12, but macos-14 .  In the meantime, it says [here](https://github.com/bancaditalia/black-it/pull/77/commits/5c22644a50184c24b690fc42fe5a7a172163ddd2) that pytables may the problem. However, the workaround seems to be a bit too expensive for us.

How about explicitly requesting macos-13 or macos-14 instead of macos -latest which gives us 12.7 ?

**Comment by adku1173** [comment]
I already had the same idea. I tested different Mac OS versions, and Mac OS-13 seems to be stable in terms of hardware (see https://github.com/adku1173/acoular/actions/runs/8736200670). Requesting only macos-13 could be a good temporary option. I will prepare a PR for that.
