### ISSUE TITLE
Question regarding example 1

### ISSUE THREAD

**Issue by LWndEn** [acoular/acoular#23]
As far as I see the simple FFT with delay is used for the data in combination with steering vector type 1. This implicitly assumes a monopole source, however trailing edge noise is known to be a dipole source. Are the results still valid after considering the above?

**Comment by esarradj** [comment]
The beamforming result in Acoular presently refers to SPL at the array center (co-ordinate origin). Thus the source type has only little influence on the result.
In future versions, other source types may be considered in the steering vector formulations. This may still not help much with the trailing edge because it is not a single dipole, but does have a quite complicated directional characteristic.
