### ISSUE TITLE
Bind loop variables

### ISSUE THREAD

**Issue by adku1173** [acoular/acoular#231]
We should better use functools `partial` method to bind variables to the optimization functions in `BeamformerCMF`, `BeamformerSODIX` and `BeamformerGridlessOrth`  (current state violates Ruff rule B023).

**Comment by esarradj** [comment]
The use of the loop variable in the function definition is intended for performance reasons. Otherwise we would need additional arguments for the function, which is used only in the same loop cycle it is defined in, but called very often. Despite late binding there remains a computational overhead from the additional argument. 
If we add an additional argument `partial` is still not needed as the optimizer functions allow to pass additional arguments. I suggest to implement this simple change and check the run time.
