### ISSUE TITLE
Confusion about digest and ext_digest in BeamformerBase

### ISSUE THREAD

**Issue by adku1173** [acoular/acoular#266]
I am slightly confused that we have two digests in the `BeamformerBase` class: 

https://github.com/acoular/acoular/blob/a12e7e9d93325ed53f5f273d41cf9548e436dfd2/acoular/fbeamform.py#L393-L400

Why is this necessary @esarradj @gherold ? I guess, I just missed something.

Can't we simply include the dependence on `freq_data.ind_low` and `freq_data.ind_high` in the normal digest? 
In addition:  why not move the `ind_low` and `ind_high` attributes from `PowerSpectra` to the Beamformer classes since `ind_low` and `ind_high` are irrelevant for the power spectra calculation and are only used for calculating the beamforming result in the respective frequency range? (I know we should keep backward compatibility, but it doesn't seem logical to me)

**Comment by esarradj** [comment]
The two digests are needed to avoid full recomputation for all frequencies in case `ind_low` or `ind_high` gets changed.

The rationale for having those attributes at the `PowerSpectra` class is because only this class knows about what indices are allowed and to which frequencies they point. I guess they could also be implemented in the `BeamformerBase` class, but then they can could not easily be validated.

A better option would be to get rid of those attributes altogether and compute only those result frequency bins that are queried by `synthetic` or an improved version of `integrate` that also takes a frequency range argument. 

However, no option would be not backward compatible.

**Comment by esarradj** [comment]
Maybe, we could heal the backward compatibility problem by guessing a sensible frequency range if none is given in an improved `integrate`.
