### ISSUE TITLE
ImportError: cannot import name MicGeom

### ISSUE THREAD

**Issue by nmnhut2010** [acoular/acoular#5]
Hi all,
I met an import error:
"ImportError: cannot import name MicGeom"
Could you please tell me how to solve?

**Comment by esarradj** [comment]
Nmnhut2010,
without further information, I can't help. Please make sure that everything is installed properly. If the problem persist, please provide some minimal example so that we can see what the problem is. Moreover, I suggest you use the [forum](https://groups.google.com/forum/#!forum/acoular-users) to ask for support.

**Comment by nmnhut2010** [comment]
Dear esarradj,

Thank you very much for your reply.
I met that error when I run acoular_demo.py file.
However, I just ran again and it works properly.
There is perhaps something wrong with my own PC.

Best regards,
Nhut M. Ngo
