### ISSUE TITLE
Cannot connect to X server

### ISSUE THREAD

**Issue by rewonc** [acoular/acoular#7]
Fresh install with conda 2.7, running on a remote machine, raises this error upon `import acoular`. Does this require one to be running acoular locally?

**Comment by esarradj** [comment]
Acoular build on traits and traitsui which needs GUI. That's why X is required, even you do not use the GUI capabilities of Acoular. Things to try:
- use  ssh -X
- use xvfb on the remote machine
- try acitivating 'null' GUI toolkit for traits ui, see http://docs.enthought.com/traitsui/traitsui_user_manual/intro.html
