### ISSUE TITLE
About _transferCoreFunc in fastFuncs.py

### ISSUE THREAD

**Issue by Moorsol** [acoular/acoular#75]
Dear Acoular Team and Users, I'm new to beamforming, when I tried to reproduct acoular's beamforming algorithms from scratch, I found something in the code that confused me.
![image](https://github.com/acoular/acoular/assets/63011882/4edcd8ff-d61a-4d04-9ff8-e7b8b2ee16d3)
![image](https://github.com/acoular/acoular/assets/63011882/5ffd9cbf-e085-4f9d-9a41-b3afc6aacaf9)
According to the paper Three-Dimensional Acoustic Source Mapping with Different Beamforming Steering Vector Formulations by Sarradj, 2012. I wonder if the code of  _transferCoreFunc should be like this:
def _transferCoreFunc(distGridToArrayCenter, distGridToAllMics, waveNumber, result):
    nGridPoints = distGridToAllMics.shape[0]
    for cntGridPoints in range(nGridPoints):
        expArg = np.float32(waveNumber[0] * (distGridToAllMics[cntGridPoints] - distGridToArrayCenter[cntGridPoints]))
        result[cntMics] = (np.cos(expArg) - 1j * np.sin(expArg)) * distGridToArrayCenter[cntGridPoints] / distGridToAllMics[cntGridPoints]

I just recently started getting into beamforming, so if I made any silly mistakes, I am sorry for wasting your time.

**Comment by gherold** [comment]
Dear Moorsol

If I understand correctly, your confusion stems from the formula in the paper stating that the distances from grid point (s) to array center / reference position (0) should be evaluated for each grid point s, yet the code seems to only take into account the very first grid point (index [0]). However, this is not actually what happens. Through the [numba guvectorize decorator](https://numba.pydata.org/numba-doc/dev/user/vectorize.html#the-guvectorize-decorator)  before the function, the process is parallelized over the grid points. In this case it means that in the finally evaluated function, the variable `distGridToAllMics` is 1D and only has as many entries as there are microphones and `distGridToArrayCenter` is an array containing one entry, namely the distance of only one of the grid points (whosever turn it is to be run through the function). As `distGridToArrayCenter` is still an array (albeit with just one entry), we have to access its contents using the indexing `[0]`. This is especially confusing since in the higher-level function `calcTransfer` the variables have different dimensions. But again, numba's guvectorize takes care of the exact manner of the parallelization and splits up the arrays, so that index `distGridToArrayCenter[0]` will have different values throughout the runtime.

I will say that this could have been better documented (when the code was accelerated using numba, we actually didn't expect people to dive into the admittedly confusing `fastFuncs.py`) and make a note of doing this at some point. Meanwhile, I hope you enjoy using Acoular :)

Best regards

Gert

**Comment by Moorsol** [comment]
Thanks for your reply, I am planning to learn something about numba to understand more about Acoular, This awesome project really helps me understand more about beamforming :)
